### PR TITLE
Implement y-sorting

### PR DESCRIPTION
**Pull request by Giwayume**
I modified "Gary_s House Interior.tscn" to use this technique.

I created a scene called CollidableBox.tscn

image

If you drop this into a level in the YSort node, you'll see a blue square representing a 1x1 area of the tilemap grid the collider will take up
image

You can increase this area by manipulating the grid_size property.

image

Once you have the correct grid area, add whatever sprite you want as the texture.

image

It's probably not going to be aligned correctly by default, because all of the textures have varying amount of white space around them. Change the texture_offset property to align the bottom corner of the sprite to the bottom corner of the blue box.

image

Then set the height property to the pixel height of the object. After which, you'll see a proper preview of the collision box.

image

I changed a bunch of things to support this. Most importantly:
- The player needs to exist inside of the YSort node in order for y sorting to impact the player. Thus, the PlayerManager singleton will attempt to place the player inside of the WorldRoot/YSort node of whatever scene is loaded.
- I renamed the player's pos_y and similar properties to pos_z. It is common practice with this style of game for z axis to be considered the jump axis.
- I renamed PlayerFloorSetter.gd to FloorSetter.gd, because this could potentially be used for enemies/npcs as well, so long as they have a floor_layers property.
- I had to separate out the player's visuals/sprite from the kinematic body in so I could manipulate the y-axis of the sprite separately from their actual y-position in order to support proper draw order.

### CODE REVIEW

**Comment by Giwayume** [comment]
Ok, this isn't y-sorting anymore, but a summary of more of the changes...

## Rendering

For controlling how sprites are drawn in terms of Z depth in the scene, I added these scenes you can drag into the level,

image

You could also just drop these scripts on existing Sprite / TileMap / AnimatedSprite nodes.

image

All of these scripts include a "height" property for controlling their z-axis height in the level:

**DepthTestCharacterAnimatedSprite** - Add to an AnimatedSprite node. Draws the sprite like a vertical billboard. Make sure to adjust "Depth Test Offset" to tell the script where on the sprite the feet of the character will be (relative to the sprite's origin position).

**DepthTestCharacterSprite** - Add to a Sprite node. Draws the sprite like a vertical billboard. Despite "Character" being in the name, you can use this for anything that is supposed to rise vertically, like a tree or a mountain. So long as it's ok with it being drawn flat. Make sure to adjust "Depth Test Offset" to tell the script where on the sprite the feet of the character will be (or the bottom of a tree, etc.), relative to the sprite's origin position.

**DepthTestFloorSprite** - Add to a Sprite node. Draws the sprite as if it's part of the floor. When layering these, choose differing height values so you don't get weird overlaps.

**DepthTestTileMap** - Add to a TileMap node. Draws the tile map as if it's part of the floor. This was only necessary for me to use in Cherry Trail 1, because the floor TileMap was both in front of and behind other objects that could potentially be drawn in front of or behind the player. In CherryTrail 4 the floor TileMap is always drawn behind the player, I just set it to a negative z-index without using this script.

And of course, still use CollidableBox for anything where you want box collision that the player can jump on.

### General Level Setup

I found this to be the easiest setup,

image

For any sprite / tilemap that will always be drawn behind the player and every NPC (and every object that could potentially be drawn in front of the player or an NPC), it's easiest to just set them to a negative z-index.

Similarly, for any sprite that will always be drawn in front of the player and every NPC, set them to a positive z-index that's above 1.

Everything else in between should use CollidableBox or one of the depth testing scripts I mentioned above.

### Transparency Limitations

Godot's depth buffer doesn't work for partially transparent objects, like shadows. So I implemented a temporal dithering effect to simulate transparency in the shader for these depth tested objects (like old Sega Genesis games). This affects the player's shadow primarily right now.

For these shadows under objects, I changed them to be completely white, then used the "modulate" property in editor to set them to a dark green.

image

## Floor Collision

I took the existing collision scripts and created nodes called Navmesh and NavmeshLayer for defining the area that the player is allowed to walk on in the level.

image

There should be one Navmesh node in the level, and it can contain multiple NavmeshLayer nodes. On each NavmeshLayer you define the height of the layer, then draw the polygon for the walking area. Your friend did a lot of good work to get this working, I just simplified the process of setting it up a bit for you.

**Comment by spikeystar** [comment]
Wow, this is really great!! I can't express how thankful I am for all the effort you put into this. It's so streamlined and organized.

I took a look and I understand the general gist of what everything you implemented is doing (a lot of the background code is just over my head for now, which is ok). I'll build some more levels later on and let you know if I run into anything, but from poking around just now I feel like this should work for what I need!

There were only a couple things I wanted to ask you about at the moment such as:

Do you know an easy way to set camera limits with this set up? For example having the camera freeze once you get to a certain position but the player is still able to move around more. Compare these two screenshots to see what I mean- I would want a scenario where the camera is fixed like the first image:
Limit 1

Limit 2

Next, I noticed these dark boxes that I didn't understand why they were located where they are or what they're for. It seems like they are related to the depth script? I don't know if there's more to say about them, but I didn't notice boxes like them in other areas.

mysterious boxes

This might just be an issue with Godot runtime/resolution settings that I need to play with but I noticed a sort of "frying" of the graphics. It most consistently seems to affect the player shadow but also some of the objects with depth scripts? I'm not sure if you have any thoughts on that, it might just be what you meant by fixing the rendering too. Gif below:

debug copy

Finally, I just wanted to throw these out there in case you had any thoughts for how compatible these features might be. These are terrain obstacles I am wanting to have in the future:
Spike tiles that when you touch put you back to a beginning position
Bubbles that for a short time will allow you to walk over lower depth water tiles that also act as a position reseter
Bouncy flowers that allow you to jump to higher areas than normal
Paths that crumble when walked on

I don't have any of the assets made yet to flesh those out but just wanted to get a pulse on how challenging you think those would be! Also feel free to point me anywhere for more info.

Thanks again, the work you did on this is really incredible to me. For both the demo and the eventual final game will definitely be crediting you for this help!

**Comment by Giwayume** [comment]
## Camera fixing

If you didn't write the SimpleCamera2D script, your friend already set this up. There's Min Pos and Max Pos on the script to adjust where the camera stops.

## Dark boxes

This is supposed to represent where height 0 is at in the level, for when you raise the Floor Height of CollidableBox above zero. You can think of it as a shadow beneath the box if the box was floating in air, and the floor was at height 0. It's supposed to help you visualize where these boxes are placed in the level relative to each other when you need to raise the height dramatically, like in Gary's house outside. But it can easily be removed if it's not helping you.

## Frying

This is the setting "Use Dither Blending" in the depth shader, which I forgot to expose on CollidableBox. Since partial transparency can't be used, it alternates which pixels are drawn each frame. At stable 60 fps it basically makes it so the edges look transparent because the pixels are swapping fast enough to not notice the swapping, but it looks bad in your gif. Maybe need to automatically disable this if low fps is detected.

## Terrain features

I can't see any potential issues with those. For most it should be sufficient to add DepthTestFloorSprite to those, and enable the "Always Update" property on the script so it's checking for position/height changes every frame if they need to move. This is disabled by default to save performance.

That script doesn't handle Sprite animation hframes / vframes like the DepthTestCharacterSprite script does right now, if you need the bubbles / crumbling floor to be animated, for example. So would need to add that in.

**Comment by Giwayume** [comment]
Actually, CollidableBox would be a better choice for those platforms. I'll try to see to make it support spritesheets.

**Pull request merged**
